version: '3.8'
services:
  jekyll:
    image: jekyll/jekyll:3.8.5
    command: jekyll serve --watch --force_polling --incremental --port 4000
    volumes:
      - .:/srv/jekyll
      - bundle:/usr/local/bundle
    ports:
      - "4000:4000"
    environment:
      JEKYLL_ENV: development

volumes:
  bundle:
